export enum ErrorCodes {
  InvalidCredentialsException = 0,
  TokenMissingException = 1,
  TokenVerificationException = 2,
  TokenExpiredException = 3,
  UnauthorizedException = 4,
  OTPGenerationException = 5,
  OTPExpiredException = 6,
  OTPVerificationException = 7,
  ForeignKeyViolationException = 8,
  DuplicateEntryException = 9,
  CreateFailedException = 10,
  UpdateFailedException = 11,
  RegistrationFailedException = 12,
  NotFoundException = 13,
  InternalServerException = 14,
  InvalidPropertiesException = 15,
  InvalidEndpointException = 16,
  UnexpectedException = 17,
  UnimplementedException = 18,
  HealthCheckFailedException = 19,
}

export enum ErrorStatusCodes {
  InvalidPropertiesException = 400,
  NotFoundException = 404,
  DuplicateEntryException = 409,
  TokenMissingException = 401,
  InternalServerException = 500,
  UnauthorizedException = 401,
  UnexpectedException = 404,
  CreateFailedException = 500,
  UpdateFailedException = 500,
  InvalidCredentialsException = 401,
  RegistrationFailedException = 500,
  InvalidEndpointException = 404,
  TokenVerificationException = 401,
  OTPGenerationException = 401,
  OTPExpiredException = 401,
  OTPVerificationException = 401,
  ForeignKeyViolationException = 512,
  UnimplementedException = 404,
  HealthCheckFailedException = 503,
}
